---
- name: Install MySQL
  apt: name={{ item }} update_cache=yes state=present
  with_items:
    - python-mysqldb
    - mysql-server

- name: start mysql service
  shell: service mysql start

- name: Removes all anonymous user accounts
  mysql_user:
    name: ''
    host_all: yes
    state: absent

- name: Create user for mysql
  mysql_user: user={{mysql_user}} host="%" password={{mysql_root_password}} priv=*.*:ALL,GRANT

- name: Create new databases with names 'test' and 'itstep'
  mysql_db:
    name: itstep
    state: present
